### ISSUE TITLE
Encoding issue with ctf4 layers name

### ISSUE THREAD

**Issue by Dune-jr** [LordSk/teeworlds#28]
Reproduce: `load ctf4`

![image](https://user-images.githubusercontent.com/355114/57782722-1ae59d00-772d-11e9-8ec9-24a723cbe0e6.png)

**Comment by LordSk** [comment]
Fixed by https://github.com/LordSk/teeworlds/commit/17fd35b7a702c9b2088c3cb3c0b66a8ca85d6b51
